global ERROR_UNKNOWN_EXCEPTION := -1
global ERROR_SUCCESS := 0x00
global ERROR_INVALID_PARAMETER := 0x01
global ERROR_NO_CONFIG_WRITE_ACCESS := 0x02
global ERROR_NO_CONFIG_READ_ACCESS := 0x03
global ERROR_INVALID_PARAM_COUNT := 0x04
global ERROR_NOT_IMPLEMENTED := 0x05